// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using laba12.data;

#nullable disable

namespace laba12.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("laba12.models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 6,
                            Description = "Лекция + Лабораторная",
                            Name = "BackEnd-разработка"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 4,
                            Description = "Лекция + Практика",
                            Name = "Базы данных"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 4,
                            Description = "Лекция + Практика",
                            Name = "Веб-программирование и дизайн"
                        });
                });

            modelBuilder.Entity("laba12.models.Enroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrolls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 0, 0, 0, DateTimeKind.Utc),
                            Grade = "5",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 0, 0, 0, DateTimeKind.Utc),
                            Grade = "4",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 0, 0, 0, DateTimeKind.Utc),
                            Grade = "3",
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("laba12.models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 0, 0, 0, DateTimeKind.Utc),
                            Group = "241-333",
                            Name = "Алиханов Богдан"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 0, 0, 0, DateTimeKind.Utc),
                            Group = "241-333",
                            Name = "Бабкин Ярослав"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 0, 0, 0, DateTimeKind.Utc),
                            Group = "241-334",
                            Name = "Богомолова Дарья"
                        });
                });

            modelBuilder.Entity("laba12.models.Enroll", b =>
                {
                    b.HasOne("laba12.models.Course", "Course")
                        .WithMany("Enrolls")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("laba12.models.Student", "Student")
                        .WithMany("Enrolls")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("laba12.models.Course", b =>
                {
                    b.Navigation("Enrolls");
                });

            modelBuilder.Entity("laba12.models.Student", b =>
                {
                    b.Navigation("Enrolls");
                });
#pragma warning restore 612, 618
        }
    }
}
