// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using laba11.data;

#nullable disable

namespace laba11.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("laba11.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 4,
                            Description = "Практика",
                            Name = "Основы технологического предпринимательства"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 4,
                            Description = "Практика",
                            Name = "Проектная деятельность"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 6,
                            Description = "Лекция + Лабораторная",
                            Name = "BackEnd-разработка"
                        },
                        new
                        {
                            Id = 4,
                            Credits = 4,
                            Description = "Лекция + Практика",
                            Name = "Базы данных"
                        },
                        new
                        {
                            Id = 5,
                            Credits = 4,
                            Description = "Лекция + Лабораторная",
                            Name = "Системный анализ"
                        },
                        new
                        {
                            Id = 6,
                            Credits = 4,
                            Description = "Лекция + Практика",
                            Name = "Веб-программирование и дизайн"
                        },
                        new
                        {
                            Id = 7,
                            Credits = 4,
                            Description = "Лекция + Пратика",
                            Name = "Математическая логика и дискретная математика"
                        },
                        new
                        {
                            Id = 8,
                            Credits = 4,
                            Description = "Лабораторная",
                            Name = "Шаблоны проектирования"
                        },
                        new
                        {
                            Id = 9,
                            Credits = 4,
                            Description = "Английский, Практика",
                            Name = "Иностранный язык"
                        },
                        new
                        {
                            Id = 10,
                            Credits = 4,
                            Description = "Практика",
                            Name = "Общая физическая подготовка"
                        });
                });

            modelBuilder.Entity("laba11.Models.Enroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrolls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4112),
                            Grade = "5",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4115),
                            Grade = "4",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4117),
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4119),
                            Grade = "4",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 4,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4121),
                            Grade = "5",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4122),
                            Grade = "3",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 6,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4124),
                            StudentId = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4126),
                            Grade = "5",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 7,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4127),
                            Grade = "4",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 9,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4130),
                            StudentId = 4
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4131),
                            Grade = "4",
                            StudentId = 5
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 8,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4133),
                            Grade = "3",
                            StudentId = 5
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4135),
                            Grade = "5",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 4,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4136),
                            StudentId = 6
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 10,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4138),
                            Grade = "4",
                            StudentId = 6
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4140),
                            Grade = "3",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4141),
                            Grade = "5",
                            StudentId = 7
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 6,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4143),
                            StudentId = 8
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 9,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4144),
                            Grade = "4",
                            StudentId = 8
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4146),
                            Grade = "5",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 7,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4147),
                            Grade = "4",
                            StudentId = 9
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 10,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4149),
                            StudentId = 9
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4151),
                            Grade = "3",
                            StudentId = 10
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 8,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4153),
                            Grade = "5",
                            StudentId = 10
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4154),
                            Grade = "4",
                            StudentId = 11
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 6,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4156),
                            StudentId = 11
                        },
                        new
                        {
                            Id = 27,
                            CourseId = 9,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4157),
                            Grade = "5",
                            StudentId = 11
                        },
                        new
                        {
                            Id = 28,
                            CourseId = 4,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4159),
                            Grade = "3",
                            StudentId = 12
                        },
                        new
                        {
                            Id = 29,
                            CourseId = 7,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4160),
                            Grade = "4",
                            StudentId = 12
                        },
                        new
                        {
                            Id = 30,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4162),
                            Grade = "5",
                            StudentId = 13
                        },
                        new
                        {
                            Id = 31,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4163),
                            StudentId = 13
                        },
                        new
                        {
                            Id = 32,
                            CourseId = 10,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4164),
                            Grade = "4",
                            StudentId = 13
                        },
                        new
                        {
                            Id = 33,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4166),
                            Grade = "3",
                            StudentId = 14
                        },
                        new
                        {
                            Id = 34,
                            CourseId = 8,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4168),
                            Grade = "5",
                            StudentId = 14
                        },
                        new
                        {
                            Id = 35,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4169),
                            StudentId = 15
                        },
                        new
                        {
                            Id = 36,
                            CourseId = 6,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4171),
                            Grade = "4",
                            StudentId = 15
                        },
                        new
                        {
                            Id = 37,
                            CourseId = 9,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4172),
                            Grade = "3",
                            StudentId = 15
                        },
                        new
                        {
                            Id = 38,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4173),
                            Grade = "4",
                            StudentId = 16
                        },
                        new
                        {
                            Id = 39,
                            CourseId = 7,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4175),
                            Grade = "5",
                            StudentId = 16
                        },
                        new
                        {
                            Id = 40,
                            CourseId = 4,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4177),
                            Grade = "3",
                            StudentId = 17
                        },
                        new
                        {
                            Id = 41,
                            CourseId = 10,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4178),
                            StudentId = 17
                        },
                        new
                        {
                            Id = 42,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4179),
                            Grade = "4",
                            StudentId = 17
                        },
                        new
                        {
                            Id = 43,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4181),
                            Grade = "5",
                            StudentId = 18
                        },
                        new
                        {
                            Id = 44,
                            CourseId = 8,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4182),
                            Grade = "4",
                            StudentId = 18
                        },
                        new
                        {
                            Id = 45,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4184),
                            StudentId = 19
                        },
                        new
                        {
                            Id = 46,
                            CourseId = 6,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4185),
                            Grade = "3",
                            StudentId = 19
                        },
                        new
                        {
                            Id = 47,
                            CourseId = 9,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4187),
                            Grade = "5",
                            StudentId = 19
                        },
                        new
                        {
                            Id = 48,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4188),
                            Grade = "4",
                            StudentId = 20
                        },
                        new
                        {
                            Id = 49,
                            CourseId = 7,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4189),
                            StudentId = 20
                        },
                        new
                        {
                            Id = 50,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4190),
                            Grade = "5",
                            StudentId = 21
                        },
                        new
                        {
                            Id = 51,
                            CourseId = 5,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4192),
                            Grade = "5",
                            StudentId = 21
                        },
                        new
                        {
                            Id = 52,
                            CourseId = 10,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4193),
                            Grade = "5",
                            StudentId = 21
                        },
                        new
                        {
                            Id = 53,
                            CourseId = 4,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4194),
                            StudentId = 22
                        },
                        new
                        {
                            Id = 54,
                            CourseId = 8,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4196),
                            Grade = "5",
                            StudentId = 22
                        },
                        new
                        {
                            Id = 55,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4197),
                            Grade = "4",
                            StudentId = 23
                        },
                        new
                        {
                            Id = 56,
                            CourseId = 6,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4201),
                            Grade = "3",
                            StudentId = 23
                        },
                        new
                        {
                            Id = 57,
                            CourseId = 9,
                            EnrolledAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(4202),
                            StudentId = 23
                        });
                });

            modelBuilder.Entity("laba11.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3752),
                            Group = "241-333",
                            Name = "Алиханов Богдан"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3758),
                            Group = "241-333",
                            Name = "Бабкин Ярослав"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3760),
                            Group = "241-334",
                            Name = "Богомолова Дарья"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3762),
                            Group = "241-334",
                            Name = "Болотная Дарья"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3764),
                            Group = "241-334",
                            Name = "Бычков Василий"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3765),
                            Group = "241-334",
                            Name = "Василенко Наталия"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3767),
                            Group = "241-334",
                            Name = "Воробьева Вероника"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3769),
                            Group = "241-334",
                            Name = "Газаматов Ислам"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3771),
                            Group = "241-334",
                            Name = "Долбышев Даниил"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3772),
                            Group = "241-334",
                            Name = "Дунаева Ева"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3774),
                            Group = "241-334",
                            Name = "Езерская Маргарита"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3776),
                            Group = "241-334",
                            Name = "Зайцев Владислав"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3777),
                            Group = "241-334",
                            Name = "Идрисов Тамерлан"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3779),
                            Group = "241-334",
                            Name = "Катышев Илья"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3781),
                            Group = "241-334",
                            Name = "Кондратенко Дмитрий"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3782),
                            Group = "241-334",
                            Name = "Погонцев Даниил"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3784),
                            Group = "241-334",
                            Name = "Романенко Николай"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3785),
                            Group = "241-334",
                            Name = "Синицина Диана"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3787),
                            Group = "241-334",
                            Name = "Смирнов Даниил"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3789),
                            Group = "241-334",
                            Name = "Топин Прохор"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3790),
                            Group = "241-334",
                            Name = "Федукина Мария"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3792),
                            Group = "241-334",
                            Name = "Хачатурян Тигран"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 4, 19, 6, 6, 51, 186, DateTimeKind.Utc).AddTicks(3794),
                            Group = "241-334",
                            Name = "Шувалов Дмитрий"
                        });
                });

            modelBuilder.Entity("laba11.Models.Enroll", b =>
                {
                    b.HasOne("laba11.Models.Course", "Course")
                        .WithMany("Enrolls")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("laba11.Models.Student", "Student")
                        .WithMany("Enrolls")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("laba11.Models.Course", b =>
                {
                    b.Navigation("Enrolls");
                });

            modelBuilder.Entity("laba11.Models.Student", b =>
                {
                    b.Navigation("Enrolls");
                });
#pragma warning restore 612, 618
        }
    }
}
